fedora-python/taskotron-python-versions

python_versions_check.py
This makes task result description a bit more readable (1 RPM per line).
It adds a URL to report issues. It also removes detail.note from
resultsdb, because it seemed unnecessary and also made the field
contents overly long for failures (all RPMs listed).
----
Log [before](https://taskotron-dev.fedoraproject.org/artifacts/all/0b1a62e4-9c73-11e6-bafa-525400d7d6a4/task_output/output.log):
```
389-ds-base-1.3.6.1-1.fc26.aarch64.rpm,389-ds-base-1.3.6.1-1.fc26.armv7hl.rpm,389-ds-base-1.3.6.1-1.fc26.i686.rpm,389-ds-base-1.3.6.1-1.fc26.x86_64.rpm require both Pythons, i.e. Python 2 and 3.
Read https://python-rpm-porting.readthedocs.io/en/latest/applications.html#are-shebangs-dragging-you-down-to-python-2 to find more information and possible cause.
Or ask at #fedora-python IRC channel for help. …
```
=> description more readable, remove note

python_versions_check.py
This should fix error reported on python3-multilib which depends on this package. The -conf subpackage only install a configuration file into /etc that is shared by both Python 2 and 3 versions of the multilib
library.
I expect this to fix an issue reported on this update: https://bodhi.fedoraproject.org/updates/python-multilib-1.2-1.fc25
I don't see anything else that could be causing the error: https://koji.fedoraproject.org/koji/rpminfo?rpmID=9235373
=> python-multilib-conf does not pull in Python 2

python_versions_check.py, taskotron_python_versions/common.py, taskotron_python_versions/two_three.py, test/functional/test_two_three.py
This is the first PR on the way to achieving #5
=> Package API class

taskotron_python_versions/common.py, taskotron_python_versions/naming_scheme.py, test/integration/test_integration.py
Fixes #13.
Report RPM names without architecture in naming_scheme check to avoid duplication.
=> Do not report architecture in the naming_scheme check

Dockerfile, README.rst, python_versions_check.py, runtask.yml, taskotron_python_versions/__init__.py, taskotron_python_versions/naming_scheme.py, taskotron_python_versions/requires.py, test/functional/test_naming_scheme.py, test/functional/test_requires.py, test/integration/test_integration.py
`libsamba-python-samba4.so` (it should be ok to fix this directly in the shared function as it should be propagated to portingdb as well)
~~Note: this task will fail even if the correct name is not provided by the required package. And I am not sure if we can check if it is provided. Maybe we could change the outcome to smth like NEEDS_INSPECTION, or look for a way to check this. Any thoughts?~~
As part of #5.
=> Requires check

taskotron_python_versions/requires.py
Also, debug log "Creating repoquery..."
Related https://github.com/fedora-python/taskotron-python-versions/issues/16
=> Disable all the repos except fedora and updates

python_versions_check.py, taskotron_python_versions/common.py, taskotron_python_versions/requires.py, test/integration/test_integration.py
* Better formatting for requires of each package
* Source rpm result (BuildRequires) on top
Also fixes an important bug, when rpm and srpm have the same NVR.
Previously it generated one result for both packages in such cases.
Now BuildRequires are displayed separately.
This was caught by the integration test.
Fixes #20
=> Improve artifact report for requires check

taskotron_python_versions/requires.py, test/functional/test_requires.py
Creating a dnf query takes quite a lot of time, and in many cases, when
there are no `python-` prefixed requires, it is not even used.
This will make sure the query does not get initialized until it is called.
=> Do not create repoquery unless needed

taskotron_python_versions/requires.py
The FPC ticket has already been discussed and the guidelines were
altered. Thus we now can use the Fedora packaging guidelines as a link
for requires check, rather than the link to the ticket.
=> Change info link for requires check

taskotron_python_versions/naming_scheme.py, test/integration/test_integration.py
Workarounds https://github.com/fedora-python/taskotron-python-versions/issues/25
Adding vdirsyncer to test_integration as a regression test.
Obsoletes https://github.com/fedora-python/taskotron-python-versions/pull/26
=> Don't check Python 3 packages for naming policy

Dockerfile, README.rst, python_versions_check.py, runtask.yml, setup.py, taskotron_python_versions/__init__.py, taskotron_python_versions/common.py, taskotron_python_versions/unversioned_shebangs.py, test/functional/common.py, test/functional/test_unversioned_shebangs.py, test/integration/test_integration.py, tox.ini
This check searches for #!/usr/bin/python and /usr/bin/env python shebangs inside RPMs. If some of these shebangs is present, check fails and the complete list of problematic files is stored into the log.
Unit and integration tests included.
=> Add unversioned shebangs check

taskotron_python_versions/two_three.py
`python-btchip-common` is common between `python2-btchip` and `python3-btchip`, because at present it shares a single udev rule necessary for the hardware to work. It contains NO python, and is being recognized as "python2" because of the prefix.
=> Include python-btchip-common in NAME_NOTS

Dockerfile, README.rst, python_versions_check.py, runtask.yml, setup.py, taskotron_python_versions/__init__.py, taskotron_python_versions/common.py, taskotron_python_versions/executables.py, taskotron_python_versions/py3_support.py, test/functional/test_py3_support.py, test/integration/test_integration.py, tox.ini
Checks if the package is ported to Python 3 if upstream supports it.
For each package which builds more Python 2 binary RPMs than Python 3 ones, check if there exists an open Bugzilla to port the package to Python 3 (see [Python 3 tracking bug](https://bugzilla.redhat.com/show_bug.cgi?id=1285816)). Encourage packagers to port their packages and close Bugzilla.
Fixes #33.
=> Add a check for Py3 support upstream

taskotron_python_versions/unversioned_shebangs.py
Reference Multiple Python Runtimes section of Fedora Packaging Guidelines for Python instead of issue in INFO_URL.
=> Update INFO_URL of shebangs check

taskotron_python_versions/py3_support.py
After a few months of not running the integration tests
I ended up with a strange error message:
<Fault 32000: 'The cookies or token provide were not valid or have
expired. You may login again to get new cookies or a new token.'>
Apparently, bugzilla.Bugzilla(...) is logging me in with some
credentials from god-knows-where. It worked last time, but in the
meantime, those credentials have expired.
I found a discussion about this at [1], and went with a solution
that disables this automatic logging in, keeping the Bugzilla
query anonymous. That fixed my issue.
[1]: https://lists.fedorahosted.org/archives/list/python-bugzilla@lists.fedorahosted.org/message/A2ZUGBFWATW676YRPJMTL2F2WYWT5RMB/
=> Make sure Bugzilla is queried without being logged in

taskotron_python_versions/naming_scheme.py, test/functional/test_naming_scheme.py
There are packages named e.g. `python3-into-dbus-python` or `python2-python-etcd`, which are
incorrectly identified as having unversioned python suffix.
=> Fix a bug in identifying ambiguous requires

README.rst, python_versions_check.py, runtask.yml, taskotron_python_versions/__init__.py, taskotron_python_versions/python_usage.py, test/functional/test_python_usage.py, test/integration/test_integration.py
See https://github.com/fedora-python/taskotron-python-versions/issues/38
This has several TODOs waiting for external factors. But the code can be reviewed nevertheless.
=> Add a test for /usr/bin/python invocation warning

python_versions_check.py, taskotron_python_versions/common.py, taskotron_python_versions/python_usage.py, taskotron_python_versions/unversioned_shebangs.py, test/functional/test_common.py, test/integration/test_integration.py
Update unversioned_shebangs task to also check for automatic shebangs mangling in build logs (#42 )
Keep the ambiguous shebangs check in place, in case brp script is disabled, but also check the build logs for the warning generated when the shebangs are automatically mangled. Fail the shebang check in both
cases.
=> Shebang check update

taskotron_python_versions/two_three.py
=> Whitelist python-cartopy-common as it does not depend on Python 2

setup.py
What's `bugzilla` on PyPI is, apparently, a weekend project from 2015.
See:
https://pypi.python.org/pypi/bugzilla
https://pypi.python.org/pypi/python-bugzilla
=> Use `python-bugzilla` rather than `bugzilla` in setup.py install_requires

tests.yml
This helps in debugging problems, because you know which package
versions were installed.
=> tests.yml: print output of DNF

taskotron_python_versions/two_three.py
The python2 requirement is for upgrade compatibility from older Fedora versions.
=> Whitelist postgresql-upgrade from two three check

.gitignore, python_versions_check.py, tests.yml
When creating the ResultsYaml format, later to be reported to ResultsDB,
list all the architectures that have been tested by this test run. This
allows people+systems to see what was tested and what was not, and
allows to query whether a specific architecture has a result or not.
=> report tested arches

.gitignore, mock.cfg, test/integration/conftest.py, test/integration/test_integration.py, tox.ini
=> Paralellize the integration tests

tests.yml
This makes the task more reliable if there are temporary network issues
with dnf repos.
=> playbook: retry dnf for network failures

README.rst, python_versions_check.py, taskotron_python_versions/__init__.py, taskotron_python_versions/python_usage.py, taskotron_python_versions/python_usage_obsoleted.py, test/integration/test_integration.py
Instead of parsing logs for `/usr/bin/python` usage, check if the source package requires
`/usr/bin/python` or `python-unversioned-command`
(https://fedoraproject.org/wiki/Changes/Move_usr_bin_python_into_separate_package).
Fix for #65.
=> Fix python_usage task

.travis.yml, Dockerfile, README.rst, mock.cfg, setup.py, taskotron_python_versions/common.py, taskotron_python_versions/python_usage.py, taskotron_python_versions/requires.py, taskotron_python_versions/two_three.py, taskotron_python_versions/unversioned_shebangs.py, test/functional/test_unversioned_shebangs.py, tests.yml, tox.ini
cc @frantisekz
Let's see what breaks.
=> Use python3 everywhere

tox.ini
- We use python-bugzilla, not bugzilla (why did it work? no idea)
- Also, no direct use of requests
=> Update tox deps

.travis.yml, tests.yml
Only the library is required to run, the whole runner pulls in a large
set of dependencies.
Also remove an ansible deprecation warning (using dnf with with_items).
=> tests.yml: remove unneeded taskotron dependency

taskotron_python_versions/two_three.py
Fixes https://github.com/fedora-python/taskotron-python-versions/issues/83
=> python-basemap-data is not a Python 2 package

taskotron_python_versions/two_three.py
- python-pyside-devel requires both Python 2 and Python 3
- the rest is version agnostic
=> Add couple more not Python 2 packages
